services:
  - type: static_site
    name: verificate-onepager
    env: static
    buildCommand: ''
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 